apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: concerned-manatee-go 
  janus-idp.io/tekton: concerned-manatee-go
  backstage.io/kubernetes-id: concerned-manatee-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: concerned-manatee-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  