apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: concerned-manatee-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: concerned-manatee-go 
  name: concerned-manatee-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: concerned-manatee-go 
